### PR TITLE
HazelcastClient to use WebAppClassloader of the context

### LINKED ISSUE #13: Thread context ClassLoader change causes serialization problem
When using client-server mode, if someone changes Thread's context ClassLoader, `HazelcastSessionManager` fails with serialization errors. We need to set the context ClassLoader to `WebAppClassLoader` before any serialization/deserialization occurs (similar to [this](https://github.com/apache/tomcat/blob/547ec0ce4a4a523f72c106046f2b3d4c4e853b4e/java/org/apache/catalina/session/FileStore.java#L227)).

Related SO question: http://stackoverflow.com/questions/41381817/hazelcast-tomcat-session-not-loading-classes-from-app-context

### PR DESCRIPTION
**Pull request by emre-aydin**
Fix #13

### CODE REVIEW

File: tomcat7/src/main/java/com/hazelcast/session/HazelcastSessionManager.java [hunk 1]
```diff
@@ -91,6 +92,10 @@ public void startInternal() throws LifecycleException {
 
         if (isClientOnly()) {
             try {
+                ClientConfig clientConfig = ClientServerLifecycleListener.getConfig();
+                clientConfig.setClassLoader(getContainer().getLoader().getClassLoader());
+                instance = HazelcastClient.newHazelcastClient(clientConfig);
+
                 instance = HazelcastClient.newHazelcastClient(ClientServerLifecycleListener.getConfig());
```
Comment (jerrinot) [inline tomcat7/src/main/java/com/hazelcast/session/HazelcastSessionManager.java]: this line should be removed?

**Comment by mesutcelik** [comment]
👍 you can squash commits into 1.
